version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
