insert into MOCK_QR_DATA (name, description) values ('imperdiet nullam', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into MOCK_QR_DATA (name, description) values ('cubilia curae donec pharetra magna', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into MOCK_QR_DATA (name, description) values ('felis ut', 'Suspendisse potenti. In eleifend quam a odio.');
insert into MOCK_QR_DATA (name, description) values ('bibendum', 'Donec ut dolor.');
insert into MOCK_QR_DATA (name, description) values ('vel dapibus at', 'Integer non velit.');
insert into MOCK_QR_DATA (name, description) values ('justo in', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into MOCK_QR_DATA (name, description) values ('integer non velit donec diam', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into MOCK_QR_DATA (name, description) values ('vestibulum ac est lacinia nisi', 'Mauris lacinia sapien quis libero.');
insert into MOCK_QR_DATA (name, description) values ('quam fringilla rhoncus', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into MOCK_QR_DATA (name, description) values ('amet consectetuer', 'Integer tincidunt ante vel ipsum.');
insert into MOCK_QR_DATA (name, description) values ('purus phasellus in felis', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into MOCK_QR_DATA (name, description) values ('amet', 'Nulla justo.');
insert into MOCK_QR_DATA (name, description) values ('duis bibendum morbi non quam', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into MOCK_QR_DATA (name, description) values ('tempus vel', 'Donec semper sapien a libero. Nam dui.');
insert into MOCK_QR_DATA (name, description) values ('ac', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into MOCK_QR_DATA (name, description) values ('vivamus', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into MOCK_QR_DATA (name, description) values ('mauris vulputate elementum nullam varius', 'Integer ac neque.');
insert into MOCK_QR_DATA (name, description) values ('tellus semper interdum', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into MOCK_QR_DATA (name, description) values ('potenti nullam porttitor lacus at', 'Nullam varius.');
insert into MOCK_QR_DATA (name, description) values ('curabitur convallis duis', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into MOCK_QR_DATA (name, description) values ('lectus pellentesque at nulla suspendisse', 'Mauris sit amet eros.');
insert into MOCK_QR_DATA (name, description) values ('elit ac nulla sed vel', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into MOCK_QR_DATA (name, description) values ('morbi quis tortor id nulla', 'Duis ac nibh.');
insert into MOCK_QR_DATA (name, description) values ('sem mauris laoreet ut', 'Pellentesque at nulla.');
insert into MOCK_QR_DATA (name, description) values ('leo maecenas', 'Praesent blandit.');
insert into MOCK_QR_DATA (name, description) values ('sed', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into MOCK_QR_DATA (name, description) values ('sapien quis', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into MOCK_QR_DATA (name, description) values ('imperdiet et commodo vulputate justo', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into MOCK_QR_DATA (name, description) values ('consequat lectus in', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into MOCK_QR_DATA (name, description) values ('eu interdum', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into MOCK_QR_DATA (name, description) values ('odio porttitor id', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into MOCK_QR_DATA (name, description) values ('ac', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into MOCK_QR_DATA (name, description) values ('elit proin', 'Fusce consequat.');
insert into MOCK_QR_DATA (name, description) values ('amet cursus id turpis integer', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into MOCK_QR_DATA (name, description) values ('cras non velit', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into MOCK_QR_DATA (name, description) values ('adipiscing lorem vitae', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into MOCK_QR_DATA (name, description) values ('venenatis non sodales sed', 'Phasellus in felis. Donec semper sapien a libero.');
insert into MOCK_QR_DATA (name, description) values ('ipsum', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into MOCK_QR_DATA (name, description) values ('hac habitasse platea dictumst', 'Ut tellus.');
insert into MOCK_QR_DATA (name, description) values ('quis orci eget orci', 'Donec ut mauris eget massa tempor convallis.');
insert into MOCK_QR_DATA (name, description) values ('rhoncus', 'Nunc purus. Phasellus in felis.');
insert into MOCK_QR_DATA (name, description) values ('consectetuer', 'Nulla ac enim.');
insert into MOCK_QR_DATA (name, description) values ('condimentum curabitur in libero ut', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into MOCK_QR_DATA (name, description) values ('nisi', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into MOCK_QR_DATA (name, description) values ('nisi vulputate nonummy maecenas tincidunt', 'Morbi a ipsum.');
insert into MOCK_QR_DATA (name, description) values ('purus eu magna vulputate', 'Morbi non quam nec dui luctus rutrum.');
insert into MOCK_QR_DATA (name, description) values ('lacinia erat vestibulum sed', 'Ut at dolor quis odio consequat varius.');
insert into MOCK_QR_DATA (name, description) values ('mattis', 'Morbi non quam nec dui luctus rutrum.');
insert into MOCK_QR_DATA (name, description) values ('eget rutrum', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into MOCK_QR_DATA (name, description) values ('ipsum dolor sit amet', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into MOCK_QR_DATA (name, description) values ('massa', 'Maecenas pulvinar lobortis est.');
insert into MOCK_QR_DATA (name, description) values ('urna', 'Maecenas tincidunt lacus at velit.');
insert into MOCK_QR_DATA (name, description) values ('aliquam quis', 'Nulla facilisi.');
insert into MOCK_QR_DATA (name, description) values ('magna at nunc', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into MOCK_QR_DATA (name, description) values ('justo morbi ut odio', 'Aenean sit amet justo. Morbi ut odio.');
insert into MOCK_QR_DATA (name, description) values ('et magnis dis', 'Vestibulum sed magna at nunc commodo placerat.');
insert into MOCK_QR_DATA (name, description) values ('vestibulum vestibulum ante', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into MOCK_QR_DATA (name, description) values ('orci', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into MOCK_QR_DATA (name, description) values ('nonummy', 'Fusce consequat. Nulla nisl.');
insert into MOCK_QR_DATA (name, description) values ('sit amet', 'In blandit ultrices enim.');
insert into MOCK_QR_DATA (name, description) values ('fusce congue', 'Duis bibendum.');
insert into MOCK_QR_DATA (name, description) values ('ipsum primis in faucibus', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into MOCK_QR_DATA (name, description) values ('consectetuer adipiscing elit proin', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into MOCK_QR_DATA (name, description) values ('nunc nisl', 'Integer ac leo.');
insert into MOCK_QR_DATA (name, description) values ('condimentum', 'Duis mattis egestas metus.');
insert into MOCK_QR_DATA (name, description) values ('in', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into MOCK_QR_DATA (name, description) values ('dolor', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into MOCK_QR_DATA (name, description) values ('eu', 'Morbi non lectus.');
insert into MOCK_QR_DATA (name, description) values ('aliquet pulvinar sed nisl nunc', 'Mauris sit amet eros.');
insert into MOCK_QR_DATA (name, description) values ('sit amet erat nulla tempus', 'Curabitur gravida nisi at nibh.');
insert into MOCK_QR_DATA (name, description) values ('rutrum nulla nunc purus', 'Phasellus sit amet erat. Nulla tempus.');
insert into MOCK_QR_DATA (name, description) values ('tellus', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into MOCK_QR_DATA (name, description) values ('ut volutpat sapien arcu', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into MOCK_QR_DATA (name, description) values ('curae', 'Curabitur at ipsum ac tellus semper interdum.');
insert into MOCK_QR_DATA (name, description) values ('facilisi cras non velit nec', 'Duis ac nibh.');
insert into MOCK_QR_DATA (name, description) values ('sit amet nulla', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into MOCK_QR_DATA (name, description) values ('ut rhoncus aliquet', 'Vivamus tortor. Duis mattis egestas metus.');
insert into MOCK_QR_DATA (name, description) values ('maecenas ut', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into MOCK_QR_DATA (name, description) values ('pellentesque volutpat dui', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into MOCK_QR_DATA (name, description) values ('convallis', 'Nulla nisl. Nunc nisl.');
insert into MOCK_QR_DATA (name, description) values ('rutrum nulla tellus in sagittis', 'In hac habitasse platea dictumst.');
insert into MOCK_QR_DATA (name, description) values ('libero quis orci nullam molestie', 'Cras non velit nec nisi vulputate nonummy.');
insert into MOCK_QR_DATA (name, description) values ('accumsan odio curabitur convallis duis', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into MOCK_QR_DATA (name, description) values ('proin interdum mauris non', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into MOCK_QR_DATA (name, description) values ('sollicitudin vitae', 'Duis ac nibh.');
insert into MOCK_QR_DATA (name, description) values ('pulvinar sed nisl nunc rhoncus', 'Etiam vel augue.');
insert into MOCK_QR_DATA (name, description) values ('mollis molestie lorem quisque', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into MOCK_QR_DATA (name, description) values ('arcu adipiscing molestie', 'Nullam varius. Nulla facilisi.');
insert into MOCK_QR_DATA (name, description) values ('quam', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into MOCK_QR_DATA (name, description) values ('aliquet maecenas', 'Pellentesque eget nunc.');
insert into MOCK_QR_DATA (name, description) values ('est', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into MOCK_QR_DATA (name, description) values ('aliquet', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into MOCK_QR_DATA (name, description) values ('potenti in eleifend', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into MOCK_QR_DATA (name, description) values ('lorem', 'Sed ante. Vivamus tortor.');
insert into MOCK_QR_DATA (name, description) values ('diam vitae quam', 'Nunc nisl.');
insert into MOCK_QR_DATA (name, description) values ('venenatis turpis', 'Duis aliquam convallis nunc.');
insert into MOCK_QR_DATA (name, description) values ('erat id', 'Pellentesque ultrices mattis odio.');
insert into MOCK_QR_DATA (name, description) values ('quisque', 'Etiam faucibus cursus urna.');
insert into MOCK_QR_DATA (name, description) values ('eu', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into MOCK_QR_DATA (name, description) values ('in purus', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
